#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
name: Go
on: [push]

jobs:
  linter:
    name: Синтаксический анализ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: Синтаксический анализ
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=30m --config=./.golangci.pipeline.yaml

  build:
    name: Сборка
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum
      - name: Установка зависимостей
        run: go mod tidy
      - name: Build
        run: go build -o ./bin/ -v ./...
