name: Go
on: [push]
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
#

env:
  SSH_TARGET: /home/vbulash/learn/week2

jobs:
  linter:
    name: Синтаксический анализ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: Синтаксический анализ
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=30m --config=./.golangci.pipeline.yaml

  build:
    name: Сборка
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum
      - name: Установка зависимостей
        run: go mod tidy
      - name: Сборка исполняемого файла чат-сервера
        run: |
          go mod download
          go build -o ./bin/chat_server cmd/grpc_server/main.go
          ls -la bin

  deploy:
    name: Развёртывание на сервере
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Развертывание на домашнем сервере
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env,bin/chat_server"
          target: $SSH_TARGET
      - name: Запуск чат-сервера
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $SSH_TARGET
            kill $(pgrep chat_server) || false
            ./chat_server
