#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
name: Go
on: [push]

env:
  REGISTRY: registry.vbulash.site
  IMAGE_NAME: chat_server
  CONTAINER_NAME: chat_server_container

jobs:
  linter:
    name: Синтаксический анализ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false
      - name: Синтаксический анализ
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          args: --timeout=30m --config=./.golangci.pipeline.yaml

  image-build-and-push:
    name: Сборка
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Установка Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: go.sum
      - name: Установка зависимостей
        run: go mod tidy
      - name: Сборка и push образа докера
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME -f Dockerfile . 
          go build -o ./bin/ -v ./...

  deploy_image:
    name: Развёртывание на сервере
    needs: image-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Развертывание на домашнем сервере через SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GITHUB_SHA, REGISTRY, IMAGE_NAME, CONTAINER_NAME
          script: |
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            docker run -d -p 50052:50052 --name $CONTAINER_NAME -t $REGISTRY/$IMAGE_NAME:$TAG_NAME
